export const banksData = [
  {
    id: 1,
    name: 'Sabadell',
    logo: '/images/banks/s_sabadell.webp',
    height: 140,
  },
  {
    id: 2,
    name: 'Bankiter',
    logo: '/images/banks/s_bankiter.webp',
    height: 44,
  },
  {
    id: 3,
    name: 'Santander',
    logo: '/images/banks/s_santander.webp',
    height: 140,
  },
  {
    id: 4,
    name: 'BBVA',
    logo: '/images/banks/s_bbva.webp',
    height: 140,
  },
  {
    id: 5,
    name: 'CaixaBank',
    logo: '/images/banks/s_caixabank.webp',
    height: 53,
  },
  {
    id: 6,
    name: 'Openbank',
    logo: '/images/banks/s_openbank.webp',
    height: 43,
  },
  {
    id: 7,
    name: 'Hipotecas.com',
    logo: '/images/banks/s_hipotecascom.webp',
    height: 24,
  },
  {
    id: 8,
    name: 'Unicaja',
    logo: '/images/banks/s_unicaja.webp',
    height: 93,
  },
  {
    id: 9,
    name: 'Evo',
    logo: '/images/banks/s_evo.webp',
    height: 84,
  },
  {
    id: 10,
    name: 'Tomamos Impulso',
    logo: '/images/banks/s_tomamos-impulso.webp',
    height: 67,
  },
  {
    id: 11,
    name: 'Abanca',
    logo: '/images/banks/s_abanca.webp',
    height: 95,
  },
  {
    id: 12,
    name: 'Cajasur',
    logo: '/images/banks/s_cajasur.webp',
    height: 57,
  },
  {
    id: 13,
    name: 'Eurocaja',
    logo: '/images/banks/s_eurocaja.webp',
    height: 140,
  },
  {
    id: 14,
    name: 'Kutxabank',
    logo: '/images/banks/s_kutxabank.webp',
    height: 84,
  },
  {
    id: 15,
    name: 'Deutsche Bank',
    logo: '/images/banks/s_deutsche-bank.webp',
    height: 50,
  },
  {
    id: 16,
    name: 'Arquia Banca',
    logo: '/images/banks/s_arquia.webp',
    height: 76,
  },
];
